### ISSUE TITLE
Work with new, unsaved buffers

### ISSUE THREAD

**Issue by gabriel-r** [TheoWinterhalter/selection-count#1]
Work with new, unsaved buffers

**Comment by TheoWinterhalter** [comment]
Hi !

You mean I should do that instead of using the Selection library ?

**Comment by gabriel-r** [comment]
I mean the counter should also be visible in a new window, where the file is not yet saved.

**Comment by TheoWinterhalter** [comment]
I see. Honestly, I thought it worked in that case (but it seems random for now, I dont' quite understand).

I'm going to give it a new try. Thanks for the issue.

Edit : Next release should fix it. Working on it.

**Comment by TheoWinterhalter** [comment]
Fixed in version 1.4.0
