### ISSUE TITLE
Status bar shows #undefined

### ISSUE THREAD

**Issue by themaninthesuitcase** [TheoWinterhalter/selection-count#2]
When selecting text the message after the count is "undefined".

![capture](https://cloud.githubusercontent.com/assets/196630/3597253/9e5b9036-0ccf-11e4-8626-cf84788de1f9.PNG)

Issue occurs regardless of file save state.

**Comment by TheoWinterhalter** [comment]
It seems that preferences settings haven't been loaded.
I thought I had fixed it before.
Which version do you use ?
What are you seeing in the console ?

Thanks for the report.

**Comment by themaninthesuitcase** [comment]
Using
Atom for windows 115
Char count 1.5.0
No errors displayed in the console.

Where are the configs stored I will get check those have been created.  I am having to install without using apm due to proxy issues.

I will also check on OSX once I have access to my macbook.

**Comment by TheoWinterhalter** [comment]
I don't where they are stored but should be able to edit them through the setting panel even though you didn't use apm. Type 'selection count' and you should be able to edit the settings.
If there are none, then the problem is that.

I don't have this issue on my macbook.

**Comment by themaninthesuitcase** [comment]
Just updated the Displayed Text value to some custom defined text and this also shows undefined.  Could be a bug in the windows version of Atom perhaps.

Will confirm on my mac, if that works next step might be a bug against atom.

**Comment by TheoWinterhalter** [comment]
Thanks a lot.
I hope it’s not me, because I don’t where this could come from…
But it might be a problem due to the order of stuff loading (as if it launched the package before loading preferences).

**Comment by themaninthesuitcase** [comment]
I've resolved the issue.

When you download and install using apm you get a folder named after the package : selection-count.  When you download the source via the package page you get a folder called char-count.  

If you rename the downloaded source folder to selection-count it works as one would expect.  Seems it's me not using apm issue rather than a bug so now closing.

**Comment by TheoWinterhalter** [comment]
Oh, indeed.

I didn't think it though, I bet changing the name hasn't been a good idea to begin with…
Thanks a lot !
