### ISSUE TITLE
It quit working after upgrading atom

### ISSUE THREAD

**Issue by mark-hahn** [TheoWinterhalter/selection-count#3]
I went from 119 to 120 and it doesn't work.  Running your spec gave 2 of 2 errors.

Windows 8.0

**Comment by TheoWinterhalter** [comment]
Can I have more info on this?
Does it crash (is there anything written in the console that is related to my package?)?

On my OS X Yosemite with Atom 120 it does work.
Have you installed it through apm or manually?

Thanks!

**Comment by mark-hahn** [comment]
It is working fine now.  I think maybe I posted this to the wrong project.  Sorry.
